# Generated by Django 3.2.8 on 2021-11-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kwarticles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kwarticles',
            name='important',
            field=models.BooleanField(default=0, verbose_name='Czy ważny'),
        ),
    ]
