# Generated by Django 3.2.8 on 2021-11-30 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kwarticles', '0002_kwarticles_important'),
    ]

    operations = [
        migrations.AddField(
            model_name='kwarticles',
            name='image',
            field=models.ImageField(null=True, upload_to='img', verbose_name='Obrazek'),
        ),
        migrations.CreateModel(
            name='KWComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50, verbose_name='Użytkownik')),
                ('comment', models.TextField(verbose_name='Komentarz')),
                ('pub_data', models.DateTimeField(auto_now_add=True, verbose_name='Data publikacji')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kwarticles.kwarticles')),
            ],
        ),
    ]
