# Generated by Django 3.2.8 on 2022-01-18 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kwarticles', '0003_auto_20211130_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='kwarticles',
            name='status',
            field=models.BooleanField(default=0, verbose_name='Opublikowany?'),
        ),
    ]
